### ISSUE TITLE
Issue with php 7.4 warning multiple ternary 

### ISSUE THREAD

**Issue by Giovanni-Petrella** [Muhammadinaam/speed-admin#5]
Hello i've this error:
![immagine](https://user-images.githubusercontent.com/70906593/125053916-e9b34e00-e0a5-11eb-89fe-b652f43fc7c0.png)

on this line: `{{request()->per_page == '' && $per_page == 10 ? 'selected' : request()->per_page == $per_page ? 'selected' : ''}}` i correct this with: `{{request()->per_page == '' && $per_page == 10 ? 'selected' : (request()->per_page == $per_page ? 'selected' : '')}}`

**Comment by Muhammadinaam** [comment]
Hi, thanks for using this package and informing me about this bug. I have fixed it by following your suggestion. Please try `composer update` in the terminal to update the package.
