### ISSUE TITLE
How overrides view

### ISSUE THREAD

**Issue by Giovanni-Petrella** [Muhammadinaam/speed-admin#6]
Hello how i publish the view to create my overrides ? (views, auth, components,crud, layouts)

**Comment by Muhammadinaam** [comment]
Hi, thanks for pointing out this. I missed the code for publishing the views. Now I have added that code. Please try `composer update` in the terminal to update the package. Then run following in the terminal to publish the views:

`php artisan vendor:publish --tag=speed-admin-views  `

**Comment by Muhammadinaam** [comment]
Please also check the config file: `config\speed-admin.php`. You can modify some parts of layout from the config:

**\config\speed-admin.php**
```
<?php

return [

    'developer_mode' => false,

    'title' => 'Speed Admin',

    'meta_description' => 'Speed Admin Project',
    'meta_author' => 'Muhammad Inaam Munir',
    'meta_keyword' => 'Speed Admin, Laravel Admin, CRUD Admin Applications',

    'admin_url' => 'admin',
    'speed_admin_assets_path' => 'vendor/speed-admin/',

    'languages' => [
        ['name' => 'English', 'locale' => 'en', 'rtl' => false],
        ['name' => 'Urdu', 'locale' => 'ur', 'rtl' => true],
    ],

    'footer_right_html' => 'Powered by&nbsp;<a href="#">Speed Admin</a>',
    'footer_left_html' => '<a href="#">CoreUI</a> © Speed Admin.',

    'user_primary_key_type' => 'integer',    // 'integer' or 'uuid'

    'enable_tenant_organization_feature' => false,

    'default_model_locale' => 'en',
    'additional_model_locales' => [
        ['name' => 'Urdu', 'locale' => 'ur'],
        ['name' => 'Arabic', 'locale' => 'ar'],
    ]
];

```

**Comment by Giovanni-Petrella** [comment]
Thanks, I am trying the package it seems to me it has a lot of potential, it is simple but effective, for some time I was looking for a starter point for new project and many did not satisfy me (infyom etc ..). In the past I used with pleasure crudbooster but although they have updated it they always use the old version of adminlte (v2), you use coreui even if I prefer adminlte v.3 so you could add support to this too in the future. There are some things missing in crudbooster but it's a great start, repeatable fields are also interesting, if you put something in with livewire it would be another big step forward. Now I test it and see if it is suitable for my refactoring project of one of my projects made with crudbooster (I would have preferred it to be adminilte v.3):  http://prismagestioneasd.prismadigitale.it
